### ISSUE TITLE
No trackball inside the slider?

### ISSUE THREAD

**Issue by erpriliano** [funwithflutter/wave-slider#1]
Is there any chance to include the trackball inside the slider? So when user slide it a small trackball appear below the wave-line as an indicator of position when user slides.

**Comment by elhe26** [comment]
Any updates?

**Comment by erpriliano** [comment]
Still no update for the moment 🙃

**Comment by diegoveloper** [comment]
I sent a PR about this requirement  https://github.com/funwithflutter/wave-slider/pull/2 , for now you could use my repo directly in pubspec.yaml:

```
  wave_slider:
    git:
      url: https://github.com/diegoveloper/wave-slider.git
```

**Comment by funwithflutter** [comment]
Sorry people for the late reply. I have not been the best at monitoring this repo. I've added @diegoveloper pull request. Will update the pub store in a couple of hours!

**Comment by funwithflutter** [comment]
The new version has trackball support.
